### PR TITLE
Added possibility to set remote base path to get logs from

### PR DESCRIPTION
**Pull request by fastlorenzo**
Added a 5th argument to `getremotelogs.sh` to be able to set the remote base path to get the logs from the C2.

### CODE REVIEW

**Comment by xychix** [comment]
Interesting but rather have this for V2.0.1
Holding back

**Comment by fastlorenzo** [comment]
@xychix it would be great to have it before that as it's a retro-compatible change with no side effect, and I need to currently patch the container before using it in prod as I'm using a different folder 😄

**Comment by MarcOverIP** [comment]
Very small fix that Im happy to approve now. 

However, @fastlorenzo  why are you using different bash operators :- and : for $4 and $5?

**Comment by fastlorenzo** [comment]
$4 was your change I think, for $5 that worked for me, not sure if this is an issue
Happy to fix if needed

**Comment by MarcOverIP** [comment]
No, $4 is from PR #135 by @yamakadi . Im not sure on the exact difference between both bash statements. But keeping them consistent has my preference. Could you please check what would be the best statement to use for both?

**Comment by yamakadi** [comment]
Hi @MarcOverIP @fastlorenzo 

You can check here for a reference on “:-“ → http://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html

The correct usage should be “:-“. I’m not sure why “:” works but it might not behave the same way across different shells.

**Comment by MarcOverIP** [comment]
Thanks for the quick reply @yamakadi :-)

Changed to :- and merged.

**Pull request merged**
