### PR TITLE
Cobalt Strike 3.14 log parsing support

### PR DESCRIPTION
**Pull request by fastlorenzo**
This commit fixes logstash to correctly parse the Cobalt Strike 3.14 logs

### CODE REVIEW

**Comment by fastlorenzo** [comment]
Fixes #13

**Comment by fastlorenzo** [comment]
@MarcOverIP any chance this can be merged in master? Did you had time to have a look at it?

**Comment by MarcOverIP** [comment]
Apologies for slow response, its holiday time so been away a bit but also recovery of a concussion has kept me offline for several weeks. Only just slowly getting back to running business.

Very much appreciate your contributions! Keep m coming.

We've got a very, very(!) big update coming to RedELK. Worked on it for months. Wanted to push it out some time ago, but said things came in between. The 3.14 logging format is only one thing of many things changed. Don't pin me down on exact date of release, my recovery is of bigger importance tbh. But shouldn't take too long.

In the mean time, Ill merge your solution into master, untested.

**Comment by fastlorenzo** [comment]
Hi man, 

Sorry to hear that, hope everything is fine now!

That's great news, looking forward to see what changes you introduced!

On my side, I used it as a basis to build a bigger project to deploy a red team environment (using Terraform to deploy and Ansible to configure).

I can't share it publicly yet as IP is company's property, but trying to find a way to share with the community.

Cheers

**Comment by MarcOverIP** [comment]
Oh, would really be interested in the TF and Ansible scripts you use! Only the RedELK part would be enough. If you can find a way to share that would be awesome!

**Pull request merged**
