### PR TITLE
Nginx full config optional (via installer)

### LINKED ISSUE #150: Reopening #148 - redelk-nginx fails to start due to upstream dependencies
Please see detailed logs below. `VERSION` set to master. You can see the jupyter reference towards the end of the log.

```
root@app7:/opt/RedELK/elkserver# vi mounts/redelk-config/etc/redelk/config.json  // setting letsencrypt to false
root@app7:/opt/RedELK/elkserver# ./install-elkserver.sh limited



    ____            _  _____  _      _  __
   |  _ \  ___   __| || ____|| |    | |/ /
   | |_) |/ _ \ / _  ||  _|  | |    | ' /
   |  _ <|  __/| (_| || |___ | |___ | . \
   |_| \__\___| \____||_____||_____||_|\_\





This script will install and configure necessary components for RedELK on ELK server



[*] Memory found available for RedELK: 7596 MB.
[!] Less than recommended 8GB memory found - yolo continuing


[*] Parameter 'limited' found. Going for the limited RedELK experience.

5 Seconds to abort

[*] Starting pre installation checks
[*] .env file already exists, skipping copy from template
[*] Setting RedELK version in docker env file
[*] Setting kibana_system ES password
[*] Setting logstash_system ES password
[*] Setting redelk_ingest ES password
[*] Redelk password in elasticsearch already defined - skipping
[*] Elastic ES password in docker template already defined - skipping
[*] Setting Kibana encryption key
[*] Adjusting memory settings for ES
[*] Setting permissions on logstash configs
[*] Setting permissions on redelk logs
[*] Setting permissions on Jupyter notebook working dir
[*] Creating custom certificate for v7.domain.tld
[*] Setting CERTS_DIR_NGINX_LOCAL
[*] Setting CERTS_DIR_NGINX_CA_LOCAL
[*] Setting TLS_NGINX_CRT_PATH
[*] Setting TLS_NGINX_KEY_PATH
[*] Setting TLS_NGINX_CA_PATH
[*] Linking docker-compose.yml to the docker file used
[*] Creating password file for easy reference
[*] Copying password file for use with jupyter notebooks
[*] Building RedELK from redelk-limited.yml file. Docker output below.

Creating network "redelk_default" with the default driver
Creating network "redelk_net" with driver "bridge"
Creating volume "redelk_kibana_data" with local driver
Creating volume "redelk_es_data" with local driver
Pulling nginx (nginx:latest)...
latest: Pulling from library/nginx
75646c2fb410: Pull complete
6128033c842f: Pull complete
71a81b5270eb: Pull complete
b5fc821c48a1: Pull complete
da3f514a6428: Pull complete
3be359fed358: Pull complete
Digest: sha256:bae781e7f518e0fb02245140c97e6ddc9f5fcf6aecc043dd9d17e33aec81c832
Status: Downloaded newer image for nginx:latest
Pulling base (outflanknl/redelk-base:master)...
master: Pulling from outflanknl/redelk-base
23884877105a: Pull complete
bc38caa0f5b9: Pull complete
2910811b6c42: Pull complete
36505266dcc6: Pull complete
07a923053093: Pull complete
776b7eaf0a03: Pull complete
bc700a6f34b5: Pull complete
60c46ea7bf2b: Pull complete
417c139cb2ee: Pull complete
aa292fbc5894: Pull complete
a216af708935: Pull complete
bf43e408d746: Pull complete
385902b690d2: Pull complete
Digest: sha256:51da403a605e5b3f5a3064837416cabc2128e4ea976110740e2ff838685b8427
Status: Downloaded newer image for outflanknl/redelk-base:master
Pulling elasticsearch (outflanknl/redelk-elasticsearch:master)...
master: Pulling from outflanknl/redelk-elasticsearch
e320e40c33f8: Pull complete
be0367056981: Pull complete
67e849725737: Pull complete
2689ab201ca3: Pull complete
054ab54cebfb: Pull complete
4e6ca8ea18d1: Pull complete
033f0d2daef0: Pull complete
3e873ca10c18: Pull complete
19c868cd4818: Pull complete
48c543a8b3de: Pull complete
37105c49f6a3: Pull complete
29b79fcef003: Pull complete
15ec243ddd8b: Pull complete
f9d0f15b9486: Pull complete
Digest: sha256:7b7ba480a2e17efef4cad780f39e9aa5d263705c54f299cc000a5262e338ff92
Status: Downloaded newer image for outflanknl/redelk-elasticsearch:master
Pulling logstash (outflanknl/redelk-logstash:master)...
master: Pulling from outflanknl/redelk-logstash
f1feca467797: Pull complete
de728266433b: Pull complete
c7e0b0a326be: Pull complete
dd4c93e74d34: Pull complete
cb37f7ac3498: Pull complete
b04c7fb7f0db: Pull complete
859788590b9a: Pull complete
232ffc518861: Pull complete
d299db49fa87: Pull complete
7386afce3da3: Pull complete
b9aeb03432ef: Pull complete
22d5e752c8a5: Pull complete
35606d5a6a80: Pull complete
c292b5f84703: Pull complete
9e21ec28ef88: Pull complete
7061b3f50223: Pull complete
Digest: sha256:d4d45b30fbd9609efaf8ec05424ce7044a0b93a4627044a00e2bac990b94add1
Status: Downloaded newer image for outflanknl/redelk-logstash:master
Pulling kibana (outflanknl/redelk-kibana:master)...
master: Pulling from outflanknl/redelk-kibana
e320e40c33f8: Already exists
8e2fe010974e: Pull complete
a199b35c70ed: Pull complete
76f7ad2fc0c2: Pull complete
f9dd2ff7c801: Pull complete
5de2791e2d43: Pull complete
69868b25af36: Pull complete
5c2d9bc0a69d: Pull complete
e6a212607f71: Pull complete
c268e9e62a14: Pull complete
3133f94edeb1: Pull complete
bbc237c741e6: Pull complete
da4c91e19bd9: Pull complete
5e933841cf64: Pull complete
4643b8a8c31e: Pull complete
Digest: sha256:94eaf937f8c83bcb9faf584c6366b459e2b46ac78369069a52f87cb26ef54b5b
Status: Downloaded newer image for outflanknl/redelk-kibana:master
Pulling certbot (certbot/certbot:latest)...
latest: Pulling from certbot/certbot
f84cab65f19f: Pull complete
d071d19751c3: Pull complete
fe68c58d2993: Pull complete
7a5d3f1b6220: Pull complete
51f83d3325a9: Pull complete
c599bb3c9a73: Pull complete
31f4ea592726: Pull complete
115b3c0c1a56: Pull complete
902d8d69d475: Pull complete
ed0c8418302f: Pull complete
19ac2c6dfc95: Pull complete
68fe1cf52bc3: Pull complete
d0a2d08c8089: Pull complete
Digest: sha256:b12bbd09b41b091abb2937721512e534c5e5aecbe2f100900afd7b3423523529
Status: Downloaded newer image for certbot/certbot:latest
Creating redelk-elasticsearch ...
Creating redelk-nginx ...
Creating redelk-elasticsearch
Creating redelk-elasticsearch ... done
Creating redelk-logstash ...
Creating redelk-nginx ... done
Creating redelk-base ...
Creating redelk-certbot ...
Creating redelk-certbot
Creating redelk-logstash ... done
Creating redelk-kibana ...
Creating redelk-certbot ... done



 Done with base setup of RedELK on ELK server
 You can now login to the following interfaces:
   - Main RedELK Kibana interface on port 443 (user: redelk, pass:skN9UlpXED4hJamOoYVC1I0FZQPF_zyT)



 !!! WARNING
 !!! WARNING - IF YOU WANT FULL FUNCTIONALITY YOU ARE NOT DONE YET !!!
 !!! WARNING

 You should really:
   - adjust the mounts/redelk-config/etc/cron.d/redelk file to include your teamservers
   - adjust all config files in mounts/redelk-config/etc/redelk to include your specifics like VT API, email server details, etc
   - adjust the .env file to match any specifics you need (e.g. using custom certificate, etc.)


root@app7:/opt/RedELK/elkserver# docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                                  PORTS                                NAMES
4a2641cf68c0        outflanknl/redelk-kibana:master          "/usr/local/bin/dumb…"   8 seconds ago       Up 6 seconds                            5601/tcp                             redelk-kibana
3c5ddda25da8        certbot/certbot                          "/bin/sh -c 'trap ex…"   9 seconds ago       Up 4 seconds                            80/tcp, 443/tcp                      redelk-certbot
a7da59231066        outflanknl/redelk-base:master            "/sbin/my_init"          9 seconds ago       Up 5 seconds                                                                 redelk-base
2d646900f20a        outflanknl/redelk-logstash:master        "/usr/local/bin/dock…"   10 seconds ago      Up 7 seconds                            0.0.0.0:5044->5044/tcp, 9600/tcp     redelk-logstash
d4eb68b2b5dd        nginx:latest                             "/docker-entrypoint.…"   12 seconds ago      Restarting (1) Less than a second ago                                        redelk-nginx
b34727b65440        outflanknl/redelk-elasticsearch:master   "/tini -- /usr/local…"   12 seconds ago      Up 10 seconds                           127.0.0.1:9200->9200/tcp, 9300/tcp   redelk-elasticsearch
root@app7:/opt/RedELK/elkserver# docker logs redelk-nginx
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/ssl-dhparams.pem.template to /etc/nginx/conf.d/ssl-dhparams.pem
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/htpasswd.users.template to /etc/nginx/conf.d/htpasswd.users
2021/04/05 23:38:40 [emerg] 25#25: host not found in upstream "redelk-kibana" in /etc/nginx/conf.d/default.conf:66
nginx: [emerg] host not found in upstream "redelk-kibana" in /etc/nginx/conf.d/default.conf:66
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/ssl-dhparams.pem.template to /etc/nginx/conf.d/ssl-dhparams.pem
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/htpasswd.users.template to /etc/nginx/conf.d/htpasswd.users
2021/04/05 23:38:43 [emerg] 25#25: host not found in upstream "redelk-jupyter" in /etc/nginx/conf.d/default.conf:105
nginx: [emerg] host not found in upstream "redelk-jupyter" in /etc/nginx/conf.d/default.conf:105
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/ssl-dhparams.pem.template to /etc/nginx/conf.d/ssl-dhparams.pem
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/htpasswd.users.template to /etc/nginx/conf.d/htpasswd.users
2021/04/05 23:38:47 [emerg] 25#25: host not found in upstream "redelk-jupyter" in /etc/nginx/conf.d/default.conf:105
nginx: [emerg] host not found in upstream "redelk-jupyter" in /etc/nginx/conf.d/default.conf:105
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/ssl-dhparams.pem.template to /etc/nginx/conf.d/ssl-dhparams.pem
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/htpasswd.users.template to /etc/nginx/conf.d/htpasswd.users
2021/04/05 23:38:48 [emerg] 25#25: host not found in upstream "redelk-jupyter" in /etc/nginx/conf.d/default.conf:105
nginx: [emerg] host not found in upstream "redelk-jupyter" in /etc/nginx/conf.d/default.conf:105
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/ssl-dhparams.pem.template to /etc/nginx/conf.d/ssl-dhparams.pem
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/htpasswd.users.template to /etc/nginx/conf.d/htpasswd.users
2021/04/05 23:38:51 [emerg] 25#25: host not found in upstream "redelk-jupyter" in /etc/nginx/conf.d/default.conf:105
nginx: [emerg] host not found in upstream "redelk-jupyter" in /etc/nginx/conf.d/default.conf:105
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/ssl-dhparams.pem.template to /etc/nginx/conf.d/ssl-dhparams.pem
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/htpasswd.users.template to /etc/nginx/conf.d/htpasswd.users
2021/04/05 23:38:54 [emerg] 25#25: host not found in upstream "redelk-jupyter" in /etc/nginx/conf.d/default.conf:105
nginx: [emerg] host not found in upstream "redelk-jupyter" in /etc/nginx/conf.d/default.conf:105
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/ssl-dhparams.pem.template to /etc/nginx/conf.d/ssl-dhparams.pem
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/htpasswd.users.template to /etc/nginx/conf.d/htpasswd.users
2021/04/05 23:38:59 [emerg] 25#25: host not found in upstream "redelk-jupyter" in /etc/nginx/conf.d/default.conf:105
nginx: [emerg] host not found in upstream "redelk-jupyter" in /etc/nginx/conf.d/default.conf:105
root@app7:/opt/RedELK/elkserver#
```

### PR DESCRIPTION
**Pull request by fastlorenzo**
The installer will comment/uncomment the include reference to the part that is used only in the "full" install mode.

Fixes #150

### CODE REVIEW

**Comment by xychix** [comment]
Bit thrown off here. is LetsEncrypt the default by now? Guess that wouldn't work in our environment does this mean wel always run dev? or should it be the other way around and make LE an additional flag.

**Comment by fastlorenzo** [comment]
@xychix nope, it's just a fix that applies only for Let's Encrypt, which is using symlinks to parent directory (so if you mount the base directory that contains the certificates, Nginx will complain as the referenced files are outside the mounted folder, and thus not accessible to docker)

**Comment by MarcOverIP** [comment]
@xychix no worries, Le's Encrypt is optional and not the default.

@fastlorenzo have you fully tested this change?

**Comment by fastlorenzo** [comment]
with the full install, yes (spinned up a clean server in Azure and did the test with this branch and LE).
There is apparently still an issue to be fixed for the limited install though, I'll try to test it this week so we can merge

**Comment by MarcOverIP** [comment]
Cool, thnx. You also tested without using LE?

**Comment by fastlorenzo** [comment]
will do ;)

**Comment by fastlorenzo** [comment]
Fully tested and ready to be merged

**Pull request merged**
