### PR TITLE
this should fetch server v2 implants back into redelk

### PR DESCRIPTION
**Pull request by xychix**
This should fetch server v2 implants back into redelk
main.log seems te be unused in new stage1 server.

### CODE REVIEW

**Comment by MarcOverIP** [comment]
Need to doublecheck if the scripts that are running in the background on the c2server are ok with these new paths.

**Comment by MarcOverIP** [comment]
To check:
[] c2server : filebeat config
[] c2server : cron job rsync command
[] c2server : copy script for downloads issued by cronjob
[] elkserver : logstash ruby script for logpath
[] elkserver : logstash ruby script for downloadpath

**Comment by maxgrim** [comment]
File URL in dashboard is incorrect. RedELK creates an URL for `downloads/[uid]_[filename]` whereas it should be `downloads/[uid]` (e.g. `downloads/N6Q37TKNAZ_whisker.exe` instead of `downloads/N6Q37TKNAZ`).

**Comment by MarcOverIP** [comment]
> File URL in dashboard is incorrect. RedELK creates an URL for `downloads/[uid]_[filename]` whereas it should be `downloads/[uid]` (e.g. `downloads/N6Q37TKNAZ_whisker.exe` instead of `downloads/N6Q37TKNAZ`).

After review, this is fixed by the background running bash script that copies `downloads/N6Q37TKNAZ` to `downloads/N6Q37TKNAZ_whisker.exe`.

PR looks good. Merging.

**Pull request merged**
