### PR TITLE
Docker mem tuning

### PR DESCRIPTION
**Pull request by MarcOverIP**
Adhering to Elastic docker memory guidelines. In detail:
- changed elkserver installer to check for and set vm.max settings
- changed elkserver installer to skip memory check for ES
- adjusted elkserver installer for NEO4J memory sizes
- modified memory specific settings in docker compose files to disable swapping

Neo4j update bugs squashed
- Dockerfile now installs proper python neo4j package
- RedELK base Jupyter notebook has an improved check for testing neo4j access

### CODE REVIEW

**Comment by fastlorenzo** [comment]
@MarcOverIP I've quickly checked the changes in the code, if I understand correctly, it nows:
- Sets the limits the Noe4J memory based on the total amount of available memory
- Sets vm.max_map_count=262144
- No longer limits the ES memory, which means it'll take the full remaining size of the host

Is this a correct understanding of the changes?

**Comment by MarcOverIP** [comment]
Correct. This is in accordance with the guideline from Elastic on Docker usage: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

**Comment by neu5ron** [comment]
they finally fixed G1GC heap settings in elasticsearch 7.x after about 7.10. If using default elasticsearch docker image and so forth - G1GC should be set because of the later java versions - but double check, this helps memory consumption drastically

**Comment by MarcOverIP** [comment]
@neu5ron thanks. Got any more info on what needs to be set? Should we also set when using < 7.10?

**Comment by neu5ron** [comment]
I would not set it in less than 7.10.. there were G1GC regressions in 7.x for a while.

put custom jvm settings in a file such as `garbage_collection.options` inside the path :
`/etc/elasticsearch/jvm.options.d/`
with config such as:
```
11-:-XX:-UseConcMarkSweepGC
11-:-XX:-UseCMSInitiatingOccupancyOnly
11-:-XX:+UseG1GC
```


which is saying any version java => 11 use G1GC. Default for 14 is G1GC by the way

to verify configured correctly, you can run in dev tools  `GET /_nodes `# then look for G1GC in `gc_collectors` field and `input_arguments` field

**Comment by MarcOverIP** [comment]
We are running version 7.10 right now. When getting /_nodes I'm seeing the argument, but not explicitly the G1GC collector:

image

Resources I find online are not clear to me if this actually enables G1GC. Got any ideas?

**Comment by neu5ron** [comment]
Yep that's it, it's enabled. all set there then

**Comment by MarcOverIP** [comment]
Thanks!

**Pull request merged**
