### PR TITLE
Moved Greynoise support to Community API

### PR DESCRIPTION
**Pull request by fastlorenzo**
Signed-off-by: fastlorenzo <git@bernardi.be>

### CODE REVIEW

**Comment by MarcOverIP** [comment]
What exactly happens when no api key is entered? Crash, spams redelk logs, writes 'error' in es record and/or sets enrich_greynoise_error tag?

**Comment by fastlorenzo** [comment]
not tested yet, PR is not yet ready for merging 😄

**Comment by MarcOverIP** [comment]
Same question on what happens when the API key is expired, or rate limited.

**Comment by fastlorenzo** [comment]
> 
> 
> Same question on what happens when the API key is expired, or rate limited.

It logs an error

**Pull request merged**
